basis/models/PackageModel.php
<?php
class PackageModel
{
  public function getPackages() {
    $database = Database::getInstance()->connect();

    $query = '
      SELECT
        *
      FROM
        packages
      WHERE
        area = ?
      AND
        status = 1
      ORDER BY
        price ASC
    ';

    $statement = $database->prepare($query);
    $statement->bind_param('i', $_SESSION['area_id']);
    $statement->execute();

    return $statement->get_result()->fetch_all(MYSQLI_ASSOC);
  }

  public function getPackage($id) {
    $database = Database::getInstance()->connect();

    $query = '
      SELECT
        *
      FROM
        packages
      WHERE
        id = ?
      AND
        area = ?
      AND
        status = 1
      ORDER BY
        price ASC
    ';

    $statement = $database->prepare($query);
    $statement->bind_param('ii', $id, $_SESSION['area_id']);
    $statement->execute();

    return $statement->get_result()->fetch_array(MYSQLI_ASSOC);
  }

  public function getPackagePriceMin() {
    $database = Database::getInstance()->connect();

    $query = '
      SELECT
        *
      FROM
        packages
      WHERE
        area = ?
      AND
        status = 1
      ORDER BY
        price ASC
      LIMIT
        1
    ';

    $statement = $database->prepare($query);
    $statement->bind_param('i', $_SESSION['area_id']);
    $statement->execute();

    return $statement->get_result()->fetch_array(MYSQLI_ASSOC);
  }

  public function getPackagePriceMax() {
    $database = Database::getInstance()->connect();

    $query = '
      SELECT
        *
      FROM
        packages
      WHERE
        area = ?
      AND
        status = 1
      ORDER BY
        price DESC
      LIMIT
        1
    ';

    $statement = $database->prepare($query);
    $statement->bind_param('i', $_SESSION['area_id']);
    $statement->execute();

    return $statement->get_result()->fetch_array(MYSQLI_ASSOC);
  }
}

basis/views/includes/analytics.php
<script>
  // (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  // (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  // m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  // })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  // ga('create', 'UA-1516174-8', 'acessonet.com.br');
  // ga('send', 'pageview');
</script>

basis/views/includes/index-business.php
<section class="slider">
  <div class="item theme-4" style="background-image: url('<?php echo $this->_asset('images/background/business-glasses.jpg'); ?>');">
    <div id="particles-js-1"></div>
    <div class="default-container">
      <div class="block text">
        <div class="primary">Tecnologia pensada para a performance de seu negócio</div>
        <div class="secondary">Utilize os serviços Acessonet e se preocupe apenas com os resultados</div>
        <a href="<?php echo $this->_url('servicos'); ?>" class="button large warning">Conhecer serviços</a>
      </div>
    </div>
  </div>
</section>

<section class="background">
  <div class="default-container">
    <div class="grid x-end y-center">
      <div class="item">
        <div class="thumbnail size-400 transparent animation floating">
          <img src="<?php echo $this->_asset('images/imac-positive.png'); ?>" alt="">
        </div>
      </div>

      <div class="item">
        <h4 class="heading">A Acessonet é sempre a melhor opção</h4>

        <ul class="list-icon">
          <li><i class="fa fa-check"></i>Os serviços da Acessonet são projetados para terem o melhor custo/benefício e garantia de qualidade.</li>
          <li><i class="fa fa-check"></i>O respeito com os clientes norteia o trabalho da Acessonet, que tem o compromisso de prestar os seus serviços com competência e qualidade.</li>
        </ul>

        <a href="<?php echo $this->_url('servicos'); ?>" class="button large expanded bordered warning gap top">Vamos conversar?</a>
      </div>
    </div>
  </div>
</section>

basis/views/includes/index-residential.php
<section class="slider">
  <div class="item <?php echo $this->slide_random['theme']; ?> reverse" style="background-image: url('<?php echo $this->slide_random['background-image']; ?>');">
    <div id="particles-js-1"></div>
    <div class="default-container">
      <div class="block text">
        <div class="primary">A sua rotina pede uma internet que acompanhe o seu ritmo</div>
        <div class="secondary">A Acessonet facilita a sua vida com uma banda larga rápida e <strong>sem linha telefônica</strong></div>

        <?php if ($this->packagePriceMin): ?>
          <div class="price-tag">
            <div class="top">Planos a partir de</div>
            <div class="total"><small>R$</small><?php echo intval($this->packagePriceMin['price']); ?><small>,<?php echo explode('.', $this->packagePriceMin['price'])[1]; ?></small></div>
            <div class="plus">Com velocidade de até <strong><?php echo $this->packagePriceMax['download']; ?></strong></div>
          </div>
        <?php endif; ?>
      </div>

      <div class="block image">
        <img src="<?php echo $this->slide_random['image']; ?>" alt="">
      </div>
    </div>

    <a href="<?php echo $this->_url('planos'); ?>">Link</a>
  </div>

  <div class="item theme-3" style="background-image: url('<?php echo $this->_asset('images/background/fiber-gray.jpg'); ?>');">
    <div class="default-container">
      <div class="block text">
        <div class="primary">Quer Acessonet na sua casa?</div>
        <div class="secondary">Escolha o seu plano ideal e solicite assinatura</div>
        <a href="<?php echo $this->_url('planos'); ?>" class="button large warning">Conhecer planos</a>
      </div>

      <div class="block image">
        <img src="<?php echo $this->_asset('images/block/family.png'); ?>" alt="">
      </div>
    </div>
  </div>
</section>

<section class="default-container">
  <ul class="list-feature">
    <li>
      <img src="<?php echo $this->_asset('images/icon-feature/yellow/fast.png'); ?>" alt="">
      <div>Banda larga</div>
    </li>
    <li>
      <img src="<?php echo $this->_asset('images/icon-feature/yellow/fiber.png'); ?>" alt="">
      <div>Redes em fibra ótica</div>
    </li>
    <li>
      <img src="<?php echo $this->_asset('images/icon-feature/yellow/noline.png'); ?>" alt="">
      <div>Sem linha telefônica</div>
    </li>
    <li>
      <img src="<?php echo $this->_asset('images/icon-feature/yellow/nofranchise.png'); ?>" alt="">
      <div>Sem franquia</div>
    </li>
  </ul>
</section>

<section class="background color-lightest color custom-4 text center">
  <div class="default-container">
    <div class="grid y-center">
      <div class="item">
        <div class="thumbnail size-400 transparent animation floating">
          <img src="<?php echo $this->_asset('images/mackbook-happy.png'); ?>" alt="">
        </div>
      </div>

      <div class="item">
        <h4 class="heading">A banda larga é ideal para</h4>

        <ul class="list-iconbox">
          <li>
            <div class="icon">
              <i class="fa fa-facebook-official"></i>
            </div>
            Usar o Facebook
          </li>
          <li>
            <div class="icon">
              <i class="fa fa-film"></i>
            </div>
            Assistir ao Netflix
          </li>
          <li>
            <div class="icon">
              <i class="fa fa-youtube-play"></i>
            </div>
            Assistir ao YouTube
          </li>
          <li>
            <div class="icon">
              <i class="fa fa-whatsapp"></i>
            </div>
            Usar o WhatsApp
          </li>
          <li>
            <div class="icon">
              <i class="fa fa-music"></i>
            </div>
            Ouvir músicas
          </li>
          <li>
            <div class="icon">
              <i class="fa fa-gamepad"></i>
            </div>
            Jogar online
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

<?php include 'section-packages.php'; ?>

basis/views/includes/section-customer-service.php
<section class="background color-lightest cover" style="background-image: url(<?php echo $this->_asset('images/background/macbook-corner.jpg'); ?>);">
  <div class="default-container">
    <div class="grid x-end y-center height-400">
      <div class="item size-4 text center">
        <h4 class="heading color muted text hiper">Ainda com dúvidas?</h4>
        <a href="<?php echo $this->_url('atendimento'); ?>" class="link more text large thin">Tente o nosso atendimento</a>
      </div>
    </div>
  </div>
</section>

basis/views/includes/section-packages.php
<section class="default-container">
  <div class="grid x-center y-center">
    <div class="item size-8 text center">
      <h4 class="heading">Quer Acessonet na sua casa?</h4>

      <div class="reading">
        <p class="">Escolha o seu plano ideal e solicite assinatura. <strong>É simples, prático e fácil.</strong></p>
        <p><a href="<?php echo $this->_url('planos'); ?>" class="button large warning">Assine já</a></p>
      </div>
    </div>
  </div>
</section>